version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9100:9000"   # php-fpm expose for nginx on host

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Mysql87@
      MYSQL_DATABASE: php_test
      MYSQL_USER: girish
      MYSQL_PASSWORD: Strong87@
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
